name: ğŸ’‹ ì‚´ë‘ì´ ë°±ì—”ë“œ ë¹Œë“œ/í…ŒìŠ¤íŠ¸ CI

on:
  pull_request:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: âœ”ï¸ ë¦¬í¬ì§€í† ë¦¬ ê°€ì ¸ì˜¤ê¸°
        uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.SUBMODULE_TOKEN }}
#           submodules: recursive

      - name: âœ”ï¸ JDK 17 ì„¤ì¹˜
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: âœ”ï¸ Gradle ëª…ë ¹ ì‹¤í–‰ì„ ìœ„í•œ ê¶Œí•œì„ ì„¤ì •
        run: chmod +x gradlew

      - name: âœ”ï¸ Gradle build
        run: ./gradlew build

      - name: âœ”ï¸ í…ŒìŠ¤íŠ¸ ê²°ê³¼ë¥¼ PRì— ì½”ë©˜íŠ¸ë¡œ ë“±ë¡
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: âœ”ï¸ í…ŒìŠ¤íŠ¸ ì‹¤íŒ¨ ì‹œ, ì‹¤íŒ¨í•œ ì½”ë“œ ë¼ì¸ì— Check ì½”ë©˜íŠ¸ë¥¼ ë“±ë¡
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}
